test:
  restrict_domain: "example.com"
  mailer:
    from: 'test@example.com'

development:
  placeholder: 1
  mailer:
    from: 'test@example.com'
  google_key: 584125599251-pefjhmb3rst8dn1vnjb4cueaqeok0fce.apps.googleusercontent.com
  google_secret: fYoKNYcpH3DHIDnWkYZvvbBS

production:
  placeholder: 1
